apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: treactor
  namespace: treactor
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.hostname }}"
